kind = "mobile"
previewPath = "/maze-mobile/"
title = "Maze Game Mobile"
version = "1.0.0"
id = "artifacts/maze-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/maze-mobile/" ]
localPort = 23750

[services.development]
run = "pnpm --filter @workspace/maze-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/maze-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/maze-mobile", "run", "serve" ]

[services.env]
PORT = "23750"
BASE_PATH = "/maze-mobile/"
